### PR TITLE
W3C compliance

### PR DESCRIPTION
**Pull request by relu91**
This PR belongs to the [new plan](https://github.com/WebThingsIO/gateway/issues/2802) of making webthings implementation aligned with the [W3C Thing Description specification](https://w3c.github.io/wot-thing-description/). Consider this as the first step towards full compliance. Nonetheless, we have already testest the change on actual devices and therefore we've updated the example section with (what we hope) useful guidelines. 

Credits: Most of the works have been carried out by @Citrullin.

### CODE REVIEW

**Comment by rzr** [comment]
may this long serie can be upstreamed into smaller changes PR  ?

**Comment by Citrullin** [comment]
> 
> 
> may this long serie can be upstreamed into smaller changes PR ?

Well, I can make one PR for the compliance and one for the examples. But this would include the changes in `ESPWebThingAdapter.h` and `Thing.h ` in one PR. I am also not sure, if the existing example would still work with that change.
But, if you wish so and it helps, sure, I can do that.

**Comment by relu91** [comment]
> Well, I can make one PR for the compliance and one for the examples. But this would include the changes in ESPWebThingAdapter.h and Thing.h in one PR. I am also not sure, if the existing example would still work with that change.
But, if you wish so and it helps, sure, I can do that.

I was thinking the same, but @rzr you have already a detailed commit history that you can navigate for reviewing. But yeah we can do a single PR containing only the alignments with w3c standard.

**Comment by relu91** [comment]
Ok talked "offline" with @Citrullin, I'm closing this PR and he'll go on and open smaller PRs.

**Comment by rzr** [comment]
ok may it be reopened but I am a bit busy now so I can't do large review that said if you find more reviewers that are ok , I'll be happy to merge it.

**Pull request closed without merging**
