### PR TITLE
example: Add LevelSensor doc and demo video

### PR DESCRIPTION
**Pull request by rzr**
makefile fixes too , I reverted it to earlier version, sorry I should have tested it more.

please confirm you can build it as explained in readme

### CODE REVIEW

**Comment by hobinjk** [comment]
Sorry, my linux VM is having issues so I unfortunately can't test the full makefile. When I try to run it locally it's unable to find the Ethernet library which I would guess is just a difference of paths between mac and linux.

**Comment by rzr** [comment]
maybe just override the arduino_host to darwin something

**Comment by hobinjk** [comment]
Unfortunately that doesn't work since it's a zip and it's piped into `tar -xJ`

**Comment by hobinjk** [comment]
Okay, testing on my ubuntu VM I'm getting the error that avr-gcc is not found despite it definitely being there. I'm also getting an interesting warning. Sorry for these being screenshots, copy-paste is not working right now:
screen shot 2018-07-27 at 10 57 17 am
screen shot 2018-07-27 at 10 51 09 am

**Comment by rzr** [comment]
I am downloading 32bit bins (so you might miss 32bits libs) maybe you can override make arduino_host=linux64

**Comment by hobinjk** [comment]
Oh right! Specifying linux64 causes everything to work perfectly

**Comment by rzr** [comment]
Of course this can be improved we can even setup a docker or travis job would that help ?

**Comment by hobinjk** [comment]
For now I'm good with just having the makefile as an option. If you want to add a dockerfile or a travis job that would be very cool

**Pull request merged**
