### PR TITLE
ArduinoJson 6

### LINKED ISSUE #14: New ArduinoJSON beta doesn't compile with ESP8266
From version 6.0.0 (beta) Arduino JSON library doesn't compile with webthing-arduino/ ESP8266.

Quote from [https://github.com/bblanchon/ArduinoJson/issues/760] 
"Indeed ArduinoJson 6 replaced the concept of JsonBuffer with the concept of JsonDocument.
To fix this error, you need either:
Downgrade ArduinoJson to 5.x (recommended as v6 is still in beta)
Upgrade your program to work with ArduinoJson 6"

### PR DESCRIPTION
**Pull request by hobinjk**
Volunteers to test on real devices would be very appreciated

Fixes #14

### CODE REVIEW

**Comment by hobinjk** [comment]
(it compiles now)

**Comment by mrstegeman** [comment]
@matiasdelellis @rzr Have either of you tested this? Is it working well?

**Comment by rzr** [comment]
Not yet but I can give a try this coming week(s).

**Comment by rzr** [comment]
May I suggest to add the above changes listed above, 

https://github.com/hobinjk/webthing-arduino/pull/1

**Comment by mrstegeman** [comment]
Moved to #99.

**Pull request closed without merging**
