### PR TITLE
example: Add LevelSensor using Ethernet

### PR DESCRIPTION
**Pull request by rzr**
It was tested on Arduino mega256 with W5100 shield and FC-28 soil moisture analog sensor

Change-Id: Ibb78e12d024df8bcbe522e013734e40a3a623b16
Origin: https://github.com/TizenTeam/webthing-esp8266
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by rzr** [comment]
More refactoring to come... if someone can test with Arduino's WiFi's shield.

**Comment by hobinjk** [comment]
Which part would you like tested with a WiFi shield? It looks like everything in this PR right now is ethernet-specific

**Comment by rzr** [comment]
yes this PR can be merged, but I'd like then to merge WiFi and Eth classes to make it more generic... I can test Eth not WiFi part and I don't want to break it ;)

**Comment by hobinjk** [comment]
Great! Sounds good to me

**Pull request merged**
